name: pyforce-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - pyvista
  - fenics-dolfinx=0.6.0
  - mpi4py
  - petsc4py
  - h5py
  - pip
  - pip:
    - tqdm
    - gmsh
    - gmsh-api
    - fluidfoam
    - scikit-learn
    - setuptools==63.0.0
    - pytest
